import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const montserratSans = localFont({
  src: "./fonts/Montserrat-Light.ttf",
  variable: "--font-montserrat-sans",
  weight: "300",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-lora-serif",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth w-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${montserratSans.variable} ${geistMono.variable} antialiased border`}
      >
        {children}
      </body>
    </html>
  );
}
